Improve link order in Classic footer
PrestaShop/ps_customeraccountlinks pull request #7
Opened 2017-04-26 16:34 UTC by fatmaBouchekoua

This PR will change the default order of the section Your account links in the classic footer.

Default order : Personal info / orders / credit slips / addresses

See Ticket : http://forge.prestashop.com/browse/BOOM-1706

2017-08-08 12:26 UTC, AlexEven commented
Hello @fatmaBouchekoua 
Can you please rebase this PR so that it can be tested and merged?
Thank you!

2017-08-08 16:18 UTC, fatmaBouchekoua commented
Hello @AlexEven ,
Done !

2017-09-13 09:32 UTC, AlexEven commented
Tested and it's all good, thanks @fatmaBouchekoua !

2017-09-13 14:33 UTC, marionf commented
It's also ok for me :)

2017-09-18 09:54 UTC, eternoendless approved these changes

2017-09-22 14:36 UTC, eternoendless requested changes

2017-09-22 14:36 UTC, eternoendless commented on ps_customeraccountlinks.php
> +                'title' => $this->trans('Addresses', array(), 'Shop.Global'),
I think you mistakenly changed the domain to an undefined one

2017-10-03 14:28 UTC, mickaelandrieu approved these changes

2017-11-21 12:25 UTC, eternoendless approved these changes

2017-11-21 12:25 UTC, eternoendless commented
Thank you @fatmaBouchekoua

2017-11-21 12:25 UTC, merged